[package]
name = "bevy_save_manager"
version = "0.1.0"
authors = ["Trung Do <dothanhtrung@pm.me>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/245project/bevy-plugin/bevy-save-manager.git"
keywords = ["bevy"]
description = "Support tool to manage saved game in Bevy"
exclude = ["assets", "examples", "tests", ".cargo"]
categories = ["game-development"]

[dependencies]
bevy = { version = ">=0.18", features = ["bevy_state", "bevy_asset"], default-features = false }
bevy_rand = { version = ">=0.14", default-features = false, features = ["wyrand"] }
rand = { version = "0.10", default-features = false }
serde = { version = "1.0" }
postcard = { version = "1.1", features = ["alloc"] }
anyhow = { version = "1.0" }
simple_crypt = { version = "0.2" }
ron = { version = "0.12" }
crossbeam-channel = { version = "0.5", default-features = false }

[dev-dependencies]
bevy = { version = ">=0.18", features = ["dynamic_linking"] }

[features]
default = []
log = ["bevy/bevy_log"]
